/* THIS FILE IS AUTOGENERATED - DO NOT EDIT */

#ifndef BIRD_REVISION_H
#define BIRD_REVISION_H

#define BIRD_REVISION "git commit 93eefdd on 2019-03-30"
#define BIRD_VERSION "93eefdd"

#endif // BIRD_REVISION_H
